### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mgajczewski** [StefH/RandomDataGenerator#16]
There are memory leaks in the library.

One here (~50MB)
`RandomizerFactory.GetRandomizer(new FieldOptionsEmailAddress()).Generate()`
Probably the stream for resources is not released.

I wanted to do a walk-around using simple FieldOptionsTextRegex for email, but it seems there is still something going on because each time I call it I'm left with hundreds of KB allocated memory more.

**Comment by StefH** [comment]
I've added a using for the resource streams.

Please test new version 1.0.13

If it's still an issue, comment / reopen this this.
