### ISSUE TITLE
Data generated is not random

### ISSUE THREAD

**Issue by MikeWilliams-UK** [StefH/RandomDataGenerator#18]
I have found that unless I insert a small delay the data generated is not random.

This is with no delay
![image](https://user-images.githubusercontent.com/13162784/137102738-95cf19a1-12f1-469d-aed6-5bf4fcb998c5.png)

This is with delay of 1ms
![image](https://user-images.githubusercontent.com/13162784/137103757-03ddb655-bae2-4701-b093-1df1e7e22171.png)

I have the following implemented as part of a Windows Forms Application using .Net Core 3.1
I am running the code in debug mode in Visual Studio 2019 [16.11.4]

```csharp
private void AddItems_Click(object sender, EventArgs e)
{
    var limit = Random.Next(5, 10);
    for (int i = 0; i < limit; i++)
    {
        AddItem();
    }
    Messages.VirtualListSize = _dataItems.Count;
}

private void AddItem()
{
    var item = new DataItem();

    item.Timestamp = DateTime.Now;
    item.CorrelationId = Guid.NewGuid().ToString();
    var randomBody = new RandomizerTextLipsum(new FieldOptionsTextLipsum { Paragraphs = 2 });
    item.Body = randomBody.Generate();
    var randomType = new RandomizerCity(new FieldOptionsCity());
    item.MessageType = randomType.Generate();

    _dataItems.Add(item);

    // Small delay is needed to make Randomizer work properly (otherwise added items are mostly duplicates)
    Thread.Sleep(1);
}
```

**Comment by kjellare** [comment]
@MikeWilliams-UK did you find a better solution for this than the delay? experiencing the same problem.

**Comment by MikeWilliams-UK** [comment]
No I never did try to fix the issue other than by adding the small delay. 1ms is hardly going to affect much :-)

**Comment by StefH** [comment]
@MikeWilliams-UK and @kjellare 
A work-around is to define the `new RandomizerTextLipsum` of `new RandomizerCity` outside of the for loop.

See also:
https://stackoverflow.com/questions/1785744/how-do-i-seed-a-random-class-to-avoid-getting-duplicate-random-values


But I'm working on a fix, so a new NuGet version will be released in some time.

**Comment by StefH** [comment]
https://github.com/StefH/RandomDataGenerator/pull/22
