### ISSUE TITLE
Credit card numbers

### ISSUE THREAD

**Issue by gderosa** [StefH/RandomDataGenerator#20]
Implementing something that would allow this
```
IRandomizerString randomizerCCN = RandomizerFactory.GetRandomizer(new FieldOptionsCCN { });
```
would be really nice to have. It should comply with Luhn algorithm etc.

**Comment by StefH** [comment]
Good idea.

Do you have any technical details on this?

**Comment by gderosa** [comment]
Not much at the moment (other than what we con google/wikipedia for). I know / I've heard of the Luhn algorithm but not sure if complying with it will be sufficient, or there are other necessary checks to ensure a number is valid in principle. We can do some more research and I'll update here if I have more details.

**Comment by StefH** [comment]
@gderosa 
I think this library https://github.com/gustavofrizzo/CreditCardValidator can be included in RandomDataGenerator to support CCN.

I'll take a look.

**Comment by StefH** [comment]
@gderosa 
It's implemented, a new version will be published to NuGet in some time.

**Comment by gderosa** [comment]
@StefH excellent job, thank you very much!!
